Adds Gnollhack and adds Notdnethack as first ascension
aoeixsz4/nhs-fork pull request #58
Opened 2022-10-30 00:20 UTC by nethack-cleaner

Adds Gnollhack as variant and updates Notdnethacks list of ascension types and makes them first ascension listed.

The file schema/addgnoll.sql
will add the records for Gnollhack tracking.

Your max(logfiles_i) may be different than mine, in which case you would need to adjust that field prior to running it.

2022-11-09 14:24 UTC, aoeixsz4 requested changes

2022-11-09 14:24 UTC, aoeixsz4 commented on nhdb-feeder.pl
> +      if ($log->{'variant'} eq 'gnoll') {
what the heck is this part about?

2022-11-09 14:24 UTC, aoeixsz4 commented on schema/addgnoll.sql
> +insert into logfiles (logfiles_i, descr, server, variant, logurl, localfile, dumpurl, oper, static, tz, fpos, lines)values (2025, 'gnollhack.org', 'hdf', 'gnoll', 'https://www.hardfought.org/xlogfile
please add these to the already existing sources schema instead of adding a new flie

2022-11-09 14:25 UTC, aoeixsz4 commented on schema/addgnoll.sql
> +insert into logfiles (logfiles_i, descr, server, variant, logurl, localfile, dumpurl, oper, static, tz, fpos, lines)values (2025, 'gnollhack.org', 'hdf', 'gnoll', 'https://www.hardfought.org/xlogfile
and just increase sequence number from the last double or triple-digit value

2022-12-02 21:18 UTC, closed without merging

2022-12-02 21:18 UTC, nethack-cleaner commented
Replacing with revision.